# Generated by Django 5.1 on 2024-09-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0002_remove_showtime_movie_remove_showtime_screen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowTime',
        ),
    ]
