# Generated by Django 5.1 on 2024-09-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='theatre_id',
        ),
    ]
