# Generated by Django 5.1 on 2024-09-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0005_remove_showtime_theatre_id'),
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='theatre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre'),
        ),
    ]
