# Generated by Django 5.1 on 2024-09-01 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('theatre_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rows', models.IntegerField(default=26)),
                ('columns', models.IntegerField(default=100)),
            ],
        ),
    ]
