# Generated by Django 5.1 on 2024-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='name',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='theatre_id',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='ticket_price',
        ),
        migrations.AlterField(
            model_name='screen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
