# Generated by Django 5.1 on 2024-09-02 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_remove_screen_columns_remove_screen_name_and_more'),
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='columns',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='screen',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='screen',
            name='rows',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='screen',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre'),
        ),
        migrations.AddField(
            model_name='screen',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screen',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
